services:

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - typer-backend-logs:/logs
      - ${PWD}/backend:/backend
    env_file:
      - .env

  db:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - typer-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  typer-backend-logs:
  typer-db-data:
