services:

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - typer-backend-logs:/logs
      - ${PWD}/backend:/backend
    env_file:
      - .env.dev

  db:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - typer-db-data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - typer-pgdata:/var/lib/pgadmin
    env_file:
      - .env.dev
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  typer-backend-logs:
  typer-db-data:
  typer-pgdata:
