version: "3"

services:

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - typer-backend-logs:/logs

  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - typer-db-data:/var/lib/postgresql/data

volumes:
  typer-backend-logs:
  typer-db-data:
