ARG PYTHON_TAG=3.10-slim

FROM python:${PYTHON_TAG}

WORKDIR /backend

COPY ./requirements.txt ./

ADD ./requirements/ ./requirements/

RUN pip install --upgrade pip && pip install -r ./requirements.txt

WORKDIR /backend/app

ENTRYPOINT [ "uvicorn", "main:app" ]

CMD [ "--host=0.0.0.0", "--reload" ]
