"""created_table_text_rating

Revision ID: b793c855227f
Revises: f7239cc1efa5
Create Date: 2022-07-07 23:48:03.731401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b793c855227f'
down_revision = 'f7239cc1efa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_ratings',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rated_text', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rated_text'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rated_by', 'rated_text', name='uix_1')
    )
    op.create_index(op.f('ix_text_ratings_id'), 'text_ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_ratings_id'), table_name='text_ratings')
    op.drop_table('text_ratings')
    # ### end Alembic commands ###
