"""change 'duration_in_seconds' field name on 'typing_sessions' table

Revision ID: 0f8799a94364
Revises: cbc7fe1f93e8
Create Date: 2025-04-19 15:52:11.290862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8799a94364'
down_revision = 'cbc7fe1f93e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('typing_sessions', 'duration_in_seconds', new_column_name='duration_in_miliseconds', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('typing_sessions', 'duration_in_miliseconds', new_column_name='duration_in_seconds', nullable=False)
    # ### end Alembic commands ###
