"""add WMP and accuracy fields to 'typing_session' table

Revision ID: 23e266902bb9
Revises: 720356688c19
Create Date: 2025-04-23 10:59:53.161692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e266902bb9'
down_revision = '720356688c19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typing_sessions', sa.Column('gross_wpm', sa.Float(), nullable=True))
    op.add_column('typing_sessions', sa.Column('net_wpm', sa.Float(), nullable=True))
    op.add_column('typing_sessions', sa.Column('accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typing_sessions', 'accuracy')
    op.drop_column('typing_sessions', 'net_wpm')
    op.drop_column('typing_sessions', 'gross_wpm')
    # ### end Alembic commands ###
