"""type and name change on 'users' table (refresh_token_hash: str -> refresh_token_hashes: list[str])

Revision ID: 68cb97eb08e7
Revises: fa2cd65da4c4
Create Date: 2025-04-30 12:06:45.680135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import ARRAY, String


# revision identifiers, used by Alembic.
revision = '68cb97eb08e7'
down_revision = 'fa2cd65da4c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hashes', ARRAY(item_type=String), nullable=True))
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_token_hashes')
    # ### end Alembic commands ###
