"""add constraint on 'texts' table: 'characters_count' cannot be null

Revision ID: 720356688c19
Revises: bf8088ec4357
Create Date: 2025-04-23 09:45:29.504608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720356688c19'
down_revision = 'bf8088ec4357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('texts', 'characters_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('texts', 'characters_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
