"""add 'characters_count' field to 'texts' table

Revision ID: bf8088ec4357
Revises: 0f8799a94364
Create Date: 2025-04-22 15:18:29.505274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8088ec4357'
down_revision = '0f8799a94364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('characters_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'characters_count')
    # ### end Alembic commands ###
