"""remove unique constraint on 'name' field on 'users' table

Revision ID: c7474ae68b1c
Revises: a8139aab8261
Create Date: 2025-03-25 10:21:31.181457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7474ae68b1c'
down_revision = 'a8139aab8261'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
