"""add 'unique name' constraint on 'users' table

Revision ID: cbc7fe1f93e8
Revises: c7474ae68b1c
Create Date: 2025-03-26 12:06:31.687754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc7fe1f93e8'
down_revision = 'c7474ae68b1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
